### ISSUE TITLE
Differences with expectedsh/go-sonic

### ISSUE THREAD

**Issue by StevenACoffman** [OGKevin/go-sonic#20]
Hey, I am trying to use sonic on a golang project, and I'm just curious oif you have a comparison with https://github.com/expectedsh/go-sonic
Thanks for your work on this!

**Comment by OGKevin** [comment]
Oef i do not. I never looked at that lib to understand the diff. I worked on my lib at the same time and published it after that one was published. So its not like i used that lib and then created my own becauses i was missing features etc. I think you would have to dig in both code bases and see which one works the best for you.
